#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install "$(grep '^uv' < requirements_dev.txt)"
uv pip install -r requirements_dev.txt --system
pre-commit install
pre-commit run --all
